"""Destatis GENESIS connector: credentials, client, and reply envelope for GENESIS-Online and Regionalstatistik."""

from .core.api import (
    GENESIS_ONLINE,
    KNOWN_HOSTS,
    OPERATIONS,
    REGIONALSTATISTIK,
    GenesisClient,
    GenesisHost,
    Operation,
    resolve_host,
)
from .core.auth import (
    OPTION_GENESIS_CREDENTIALS,
    DestatisCredentials,
    credentials_from_options,
)
from .core.envelope import (
    GenesisEnvelope,
    GenesisIdent,
    GenesisStatus,
    HelloWorldReply,
    LoginCheckReply,
    inspect_response,
    parse_json_reply,
    raise_for_logincheck,
    raise_for_status_block,
)
from .core.errors import (
    GenesisAuthError,
    GenesisBackendError,
    GenesisEmptySelection,
    GenesisError,
    GenesisJobAccepted,
    GenesisMaintenance,
    GenesisResultTooLarge,
    GenesisUnknownEnvelope,
    GenesisUnknownTable,
    MissingCredentialsError,
    WrongHostCredentialsError,
)
from .core.redact import redact_json, redact_text, secret_variants

__all__ = [
    "GENESIS_ONLINE",
    "KNOWN_HOSTS",
    "OPERATIONS",
    "OPTION_GENESIS_CREDENTIALS",
    "REGIONALSTATISTIK",
    "DestatisCredentials",
    "GenesisAuthError",
    "GenesisBackendError",
    "GenesisClient",
    "GenesisEmptySelection",
    "GenesisEnvelope",
    "GenesisError",
    "GenesisHost",
    "GenesisIdent",
    "GenesisJobAccepted",
    "GenesisMaintenance",
    "GenesisResultTooLarge",
    "GenesisStatus",
    "GenesisUnknownEnvelope",
    "GenesisUnknownTable",
    "HelloWorldReply",
    "LoginCheckReply",
    "MissingCredentialsError",
    "Operation",
    "WrongHostCredentialsError",
    "credentials_from_options",
    "inspect_response",
    "parse_json_reply",
    "raise_for_logincheck",
    "raise_for_status_block",
    "redact_json",
    "redact_text",
    "resolve_host",
    "secret_variants",
]
